api contexts alter
- Separate API version paths for each platform
- Added new platform function interface, and implemented and extracted functions of services
- Adjust the CI process to automatically generate and check the compilation environment file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,11 +8,7 @@ on:
 
 jobs:
   build:
-    # strategy:
-    #   matrix:
-    #     os: [ubuntu-latest, windows-latest, macos-latest]
     runs-on: windows-latest
-    # runs-on: ${{ matrix.os }}
 
     steps:
     - name: Checkout code
@@ -24,7 +20,6 @@ jobs:
         go-version: "1.24.3"
 
     - name: Set Go environment variables
-      # if: matrix.os == 'windows-latest'
       run: echo "GOPATH=%USERPROFILE%\\go" >> $GITHUB_ENV
 
     - name: Cache Go modules
@@ -40,8 +35,20 @@ jobs:
     - name: Install dependencies
       run: go mod tidy
 
+    - name: Generate interface checks (CI only)
+      run: |
+        echo "Generating genInterfaceCheck.go..."
+        go generate ./internal/cmd/genchecks/handler
+        if [ $? -ne 0 ]; then
+          echo "❌ Interface generation failed"
+          exit 1
+        fi
+
     - name: Build
-      run: go build ./...
+      run: |
+        echo "Building project..."
+        go build ./...
+      shell: bash
 
     - name: Run tests
       run: go test -v ./...
